
stof_doctrine_extensions:
    default_locale: fr_FR
    orm:
        default:
            sortable: true
            loggable: true
            sluggable: true
            tree: true
            timestampable: false # not needed: listeners are not enabled by default