<?php

namespace App\ProjectBundle\Repository;

use App\CoreBundle\Repository\RepositoryCore;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends RepositoryCore
{

}
